# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pi/v1/common.proto\x12\x06\x61pi.v1\"M\n\tSatellite\x12\x10\n\x08norad_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07tle_ln1\x18\x03 \x01(\t\x12\x0f\n\x07tle_ln2\x18\x04 \x01(\t\"y\n\rEphemerisData\x12\x11\n\tds50_time\x18\x01 \x01(\x01\x12\x10\n\x08mse_time\x18\x02 \x01(\x01\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\t\n\x01z\x18\x05 \x01(\x01\x12\n\n\x02vx\x18\x06 \x01(\x01\x12\n\n\x02vy\x18\x07 \x01(\x01\x12\n\n\x02vz\x18\x08 \x01(\x01\x42\x13Z\x11\x61pi/v1/gen/;apiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021api/v1/gen/;apiv1'
  _globals['_SATELLITE']._serialized_start=31
  _globals['_SATELLITE']._serialized_end=108
  _globals['_EPHEMERISDATA']._serialized_start=110
  _globals['_EPHEMERISDATA']._serialized_end=231
# @@protoc_insertion_point(module_scope)
