# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/main.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/v1/main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.v1.core import ephem_pb2 as api_dot_v1_dot_core_dot_ephem__pb2
from api.v1.core import prop_pb2 as api_dot_v1_dot_core_dot_prop__pb2
from api.v1 import info_pb2 as api_dot_v1_dot_info__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi/v1/main.proto\x12\x06\x61pi.v1\x1a\x17\x61pi/v1/core/ephem.proto\x1a\x16\x61pi/v1/core/prop.proto\x1a\x11\x61pi/v1/info.proto\x1a\x1bgoogle/protobuf/empty.proto2\xad\x01\n\nPropagator\x12\x34\n\x04Info\x12\x16.google.protobuf.Empty\x1a\x14.api.v1.InfoResponse\x12\x31\n\x04Prop\x12\x13.api.v1.PropRequest\x1a\x14.api.v1.PropResponse\x12\x36\n\x05\x45phem\x12\x14.api.v1.EphemRequest\x1a\x15.api.v1.EphemResponse0\x01\x42\x13Z\x11\x61pi/v1/gen/;apiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021api/v1/gen/;apiv1'
  _globals['_PROPAGATOR']._serialized_start=127
  _globals['_PROPAGATOR']._serialized_end=300
# @@protoc_insertion_point(module_scope)
