# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.v1.core import ephem_pb2 as api_dot_v1_dot_core_dot_ephem__pb2
from api.v1.core import prop_pb2 as api_dot_v1_dot_core_dot_prop__pb2
from api.v1 import info_pb2 as api_dot_v1_dot_info__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PropagatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/api.v1.Propagator/Info',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_v1_dot_info__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Prop = channel.unary_unary(
                '/api.v1.Propagator/Prop',
                request_serializer=api_dot_v1_dot_core_dot_prop__pb2.PropRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_core_dot_prop__pb2.PropResponse.FromString,
                _registered_method=True)
        self.Ephem = channel.unary_stream(
                '/api.v1.Propagator/Ephem',
                request_serializer=api_dot_v1_dot_core_dot_ephem__pb2.EphemRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_core_dot_ephem__pb2.EphemResponse.FromString,
                _registered_method=True)


class PropagatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ephem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropagatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api_dot_v1_dot_info__pb2.InfoResponse.SerializeToString,
            ),
            'Prop': grpc.unary_unary_rpc_method_handler(
                    servicer.Prop,
                    request_deserializer=api_dot_v1_dot_core_dot_prop__pb2.PropRequest.FromString,
                    response_serializer=api_dot_v1_dot_core_dot_prop__pb2.PropResponse.SerializeToString,
            ),
            'Ephem': grpc.unary_stream_rpc_method_handler(
                    servicer.Ephem,
                    request_deserializer=api_dot_v1_dot_core_dot_ephem__pb2.EphemRequest.FromString,
                    response_serializer=api_dot_v1_dot_core_dot_ephem__pb2.EphemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.Propagator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.Propagator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Propagator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.Propagator/Info',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api_dot_v1_dot_info__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.Propagator/Prop',
            api_dot_v1_dot_core_dot_prop__pb2.PropRequest.SerializeToString,
            api_dot_v1_dot_core_dot_prop__pb2.PropResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ephem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.v1.Propagator/Ephem',
            api_dot_v1_dot_core_dot_ephem__pb2.EphemRequest.SerializeToString,
            api_dot_v1_dot_core_dot_ephem__pb2.EphemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
