# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/core/ephem.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/v1/core/ephem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.v1 import common_pb2 as api_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi/v1/core/ephem.proto\x12\x06\x61pi.v1\x1a\x13\x61pi/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n\rEphemTimeGrid\x12\x17\n\x0ftime_start_ds50\x18\x01 \x01(\x01\x12\x32\n\x0etime_start_utc\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rtime_end_ds50\x18\x03 \x01(\x01\x12\x30\n\x0ctime_end_utc\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x14known_time_step_ds50\x18\x05 \x01(\x01H\x00\x12 \n\x16known_time_step_period\x18\x06 \x01(\tH\x00\x12\x1b\n\x11\x64ynamic_time_step\x18\x07 \x01(\x08H\x00\x42\x10\n\x0etime_step_type\"f\n\tEphemTask\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\x12\x1e\n\x03sat\x18\x02 \x01(\x0b\x32\x11.api.v1.Satellite\x12(\n\ttime_grid\x18\x03 \x01(\x0b\x32\x15.api.v1.EphemTimeGrid\"\x98\x01\n\x0c\x45phemRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12%\n\nephem_type\x18\x02 \x01(\x0e\x32\x11.api.v1.EphemType\x12/\n\x10\x63ommon_time_grid\x18\x03 \x01(\x0b\x32\x15.api.v1.EphemTimeGrid\x12 \n\x05tasks\x18\x04 \x03(\x0b\x32\x11.api.v1.EphemTask\"b\n\x08\x45phemOut\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\x12)\n\nephem_data\x18\x02 \x03(\x0b\x32\x15.api.v1.EphemerisData\x12\x1a\n\x12\x65phem_points_count\x18\x03 \x01(\x03\"m\n\rEphemResponse\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x11\n\tstream_id\x18\x02 \x01(\x03\x12\x17\n\x0fstream_chunk_id\x18\x03 \x01(\x03\x12 \n\x06result\x18\x04 \x01(\x0b\x32\x10.api.v1.EphemOut*=\n\tEphemType\x12\x14\n\x10\x45phemPlaceholder\x10\x00\x12\x0c\n\x08\x45phemEci\x10\x01\x12\x0c\n\x08\x45phemJ2K\x10\x02\x42\x13Z\x11\x61pi/v1/gen/;apiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.core.ephem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021api/v1/gen/;apiv1'
  _globals['_EPHEMTYPE']._serialized_start=840
  _globals['_EPHEMTYPE']._serialized_end=901
  _globals['_EPHEMTIMEGRID']._serialized_start=90
  _globals['_EPHEMTIMEGRID']._serialized_end=368
  _globals['_EPHEMTASK']._serialized_start=370
  _globals['_EPHEMTASK']._serialized_end=472
  _globals['_EPHEMREQUEST']._serialized_start=475
  _globals['_EPHEMREQUEST']._serialized_end=627
  _globals['_EPHEMOUT']._serialized_start=629
  _globals['_EPHEMOUT']._serialized_end=727
  _globals['_EPHEMRESPONSE']._serialized_start=729
  _globals['_EPHEMRESPONSE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
