# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/core/prop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/v1/core/prop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.v1 import common_pb2 as api_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/v1/core/prop.proto\x12\x06\x61pi.v1\x1a\x13\x61pi/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n\x08PropTask\x12\x1e\n\x03sat\x18\x01 \x01(\x0b\x32\x11.api.v1.Satellite\x12\x0c\n\x04time\x18\x02 \x01(\x01\x12,\n\x08time_utc\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"b\n\x0bPropRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12#\n\ttime_type\x18\x02 \x01(\x0e\x32\x10.api.v1.TimeType\x12\x1e\n\x04task\x18\x03 \x01(\x0b\x32\x10.api.v1.PropTask\"E\n\x0cPropResponse\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12%\n\x06result\x18\x04 \x01(\x0b\x32\x15.api.v1.EphemerisData*%\n\x08TimeType\x12\x0b\n\x07TimeMse\x10\x00\x12\x0c\n\x08TimeDs50\x10\x01\x42\x13Z\x11\x61pi/v1/gen/;apiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.core.prop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021api/v1/gen/;apiv1'
  _globals['_TIMETYPE']._serialized_start=363
  _globals['_TIMETYPE']._serialized_end=400
  _globals['_PROPTASK']._serialized_start=88
  _globals['_PROPTASK']._serialized_end=190
  _globals['_PROPREQUEST']._serialized_start=192
  _globals['_PROPREQUEST']._serialized_end=290
  _globals['_PROPRESPONSE']._serialized_start=292
  _globals['_PROPRESPONSE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
